### ISSUE TITLE
About the network's trained model

### ISSUE THREAD

**Issue by small-beebee** [ShuhanChen/PGAR_ECCV20#2]
First of all, thank you very much for your outstanding contribution. But I have a request, I hope you can upload the weights trained on the NJUD+NLPR dataset, because I can't reproduce the results of your version. If you can do this, I would be very grateful！

**Comment by ShuhanChen** [comment]
The model trained on NJUD+NLPR, and pre-computed saliency maps:
Baidu disk: https://pan.baidu.com/s/1RM5Ssx2HZ35p_Pqs0ZOmmA (cpuu)
